name: stock-service
server:
  port: 8003
  servlet:
    context-path: /

spring:
  #緩存管理
  cache:
    type: redis
    redis:
      time-to-live: 3600000 #過期時間(毫秒)
#      建議使用緩存前綴  且不指定分區名前綴
#      key-prefix: CACHE_ #緩存的前綴 沒有默認使用緩存名作為前綴
      use-key-prefix: true #是否使用緩存前綴
      cache-null-values: true #(重要) 是否緩存空值 防止緩存穿透
  #    cache-names: qq

  #Redis 配置 & 線程池
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 3
        min-idle: 2
        max-idle: 3
        max-wait: 1

  application:
    name: stock-service #服務名*服務註冊與發現時使用 如果是多台會共用名

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13308/e_stock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tony0204



mybatis:
  mapper-locations: classpath*:mapper/*.xml #MyBatis映射文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #開啟SQL語句打印


seata:
  application-id: stock-service
  tx-service-group: my_test_tx_group

